### ISSUE TITLE
Skip long queries?

### ISSUE THREAD

**Issue by duzenko** [khmm12/knex-tiny-logger#10]
We sometimes need to insert binary blobs into the DB, which overflows the entire console buffer and hangs the server for a while when debugging
I would like an option to limit individual queries to e.g. first 1KB
Please advise
![image](https://user-images.githubusercontent.com/1481807/112465745-bc989500-8d6d-11eb-810e-18abd18bd2a2.png)

**Comment by khmm12** [comment]
Hey @duzenko 👋

I see 2 solutions:

1. Disable bindings.
2. Skip output before sending to your logger.

```js
knexTinyLogger(knex, { bindings: false })
```


```js
function shouldBeLogged(parts) {
   const length = parts.reduce(parts, (memo, part) => typeof part === 'string' ? memo + part.length : memo, 0)
   return length <= 1000
}

function filterOutput(logger) {
   return (...parts) => {
     if (shouldBeLogged(parts)) logger(...parts)
   } 
}

knexTinyLogger(knex, { logger: filterOutput(console.log) })
```

**Comment by duzenko** [comment]
My version:
```
		logger: ( ...parts ) => {
			const check = ( x ) => typeof x === 'string' && x.length > 0x400 && x.includes( 'data:image/png;base64' );
			const shortened = parts.map( part => check( part ) ? ( part.substr( 0, 0x400 ) + '…' ) : part );
			require( 'debug' )( 'pss2:knex' )( ...shortened );
		},
```
Although I'd still love to be able to skip individual sql query parts instead of the entire query
