### ISSUE TITLE
logger incorrectly logs selects where column = 0

### ISSUE THREAD

**Issue by adamlounds** [khmm12/knex-tiny-logger#2]
eg

> SQL (4.097 ms) select * from \`test\` where \`numbercol\` =  and \`time\` < 1535796000

Probably caused by `bindings[index]` being false in
`const binding = bindings[index] ? JSON.stringify(bindings[index]) : ''`

**Comment by khmm12** [comment]
Hey @adamlounds. Resolved in 1.1.0 😊
