### ISSUE TITLE
logger does not log if there was an error in the sql

### ISSUE THREAD

**Issue by adamlounds** [khmm12/knex-tiny-logger#3]
eg if I select from a non-existent table, logger does not log that the db call was made.

**Comment by khmm12** [comment]
Hey @adamlounds. 

Should be fixed in v1.1.0. Tested with postgres:
<img width="534" alt="2018-07-05 17 34 21" src="https://user-images.githubusercontent.com/4437249/42329599-b5783a5e-8079-11e8-8ffe-769d610be21f.png">
