### ISSUE TITLE
lib/index.js removes flow typing

### ISSUE THREAD

**Issue by taybin** [khmm12/knex-tiny-logger#4]
I'm importing knex-tiny-logger into my nodejs project that uses flowtype and I have to setup a flowtyped file containing the very definitions already in src/index.js.  Is there a way to publish the file and preserve the flowtyping for those of us who want to check the types?

https://github.com/flow-typed/flow-typed/wiki/FAQs#what-is-the-preferred-way-for-a-module-to-provide-its-own-libdef

Copying them to `index.js.flow` or something like that looks to be the preferred method.

**Comment by khmm12** [comment]
Hello @taybin. Thank for your feedback! 

v2.0.0 release includes flow and typescript typings.
